baseURL: 'http://example.org/'
author: 
  name: Jacob953
  email: i@jacob953.com
  role: Day-dreamer, open-source ethusastic and currently working at Huawei
  intro: makes funny things
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0  International License.
languageCode: en-us
title: JACO GARDEN
theme: three4th

params: 
  subscribe: true
  link:
    - name: github
      url: https://github.com/Jacob953
    - name: linkedin
      url: https://www.linkedin.com/in/junfeng-yu-578456248/

menu:
  main:
    - name: Garden
      url: /
      weight: 1
      post: caret-down
    - name: Essays
      url: /essays
      parent: Garden
      weight: 1
    - name: Notes
      url: /notes
      parent: Garden
      weight: 2
    - name: Lanes
      url: /lanes
      parent: Garden
      weight: 3
    - name: Library
      url: /library
      parent: Garden
      weight: 4
    - name: Cassette
      url: /cassette
      weight: 2
    - name: Wiki
      url: https://github.com/Jacob953/hugo-three4th/wiki
      weight: 3
      post: link

enableGitInfo: true
lastmod: ["lastmod", ":fileModTime", ":default"]